package handler

import (
	"crypto/ed25519"
	"encoding/hex"
	"testing"
)

func TestDataSchemaCompatible(t *testing.T) {
	cases := []struct {
		name     string
		received string
		want     bool
	}{
		{"exact same", "1.0", true},
		{"same major, patch ok", "1.0.4", true},
		{"unknown minor", "1.0.0", true},
		{"newer minor", "1.1", true}, // minor is advisory, not blocking
		{"older major", "0.9", false},
		{"newer major", "2.0", false},
		{"garbage", "banana2", false},
	}
	for _, tc := range cases {
		t.Run(tc.name, func(t *testing.T) {
			if got := dataSchemaCompatible(tc.received); got != tc.want {
				t.Errorf("dataSchemaCompatible(%q) = %v, want %v", tc.received, got, tc.want)
			}
		})
	}
}

func TestVerifySignatureHex(t *testing.T) {
	pub, priv, err := ed25519.GenerateKey(nil)
	if err != nil {
		t.Fatal(err)
	}

	message := []byte("content-hash-to-sign")
	goodSig := hex.EncodeToString(ed25519.Sign(priv, message))

	if err := verifySignatureHex(hex.EncodeToString(pub), message, goodSig); err != nil {
		t.Errorf("valid signature rejected: %v", err)
	}

	// Tampered message must fail.
	if err := verifySignatureHex(hex.EncodeToString(pub), []byte("content-hash-to-tamper"), goodSig); err == nil {
		t.Error("tampered message accepted")
	}

	// Tampered signature must fail.
	badSig := hex.EncodeToString(ed25519.Sign(priv, []byte("other")))
	if err := verifySignatureHex(hex.EncodeToString(pub), message, badSig); err == nil {
		t.Error("signature over different data accepted")
	}

	// Malformed inputs must fail, not panic.
	if err := verifySignatureHex("zz", message, goodSig); err == nil {
		t.Error("malformed public key accepted")
	}
	if err := verifySignatureHex(hex.EncodeToString(pub), message, "not-hex"); err == nil {
		t.Error("malformed signature accepted")
	}
}

// TestHashSnapshotRecords cross-checks the Go BLAKE3 re-hash against a value
// produced by the Rust node (blake3 crate), hashing the same wire bytes:
// per chunk [8-byte big-endian record count] ++ [compact JSON records array].
func TestHashSnapshotRecords(t *testing.T) {
	chunkOne := []byte(`[{"file_id":"f1","version_number":1,"version_hash":"h1","shard_count":3}]`)
	chunkTwo := []byte(`[]`)

	got, err := hashSnapshotRecords([][]byte{chunkOne, chunkTwo})
	if err != nil {
		t.Fatalf("hashSnapshotRecords: %v", err)
	}

	// Generated by the Rust snapshot hasher over the identical bytes.
	const rustExpected = "de4543aa6e15ef448d335d5e76e9a2fcef679391c6c4c82f23e829dca211641f"
	if got != rustExpected {
		t.Errorf("hash = %s, want %s", got, rustExpected)
	}

	// Plain JSON object inside a chunk (not an array) must be rejected.
	if _, err := hashSnapshotRecords([][]byte{[]byte(`{"file_id":"x"}`)}); err == nil {
		t.Error("non-array records should error")
	}
}
